# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-16 17:03
from __future__ import unicode_literals

from django.db import migrations


def add_choices(apps, schema_editor):
    Question = apps.get_model('app', 'Question')
    Choice = apps.get_model('app', 'Choice')
    for q in Question.objects.all():
        c = Choice(question=q, choice_text="Yes", votes=0)
        c.save()
        c = Choice(question=q, choice_text="No", votes=0)
        c.save()
        c = Choice(question=q, choice_text="Maybe", votes=0)
        c.save()


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_choices)
    ]
