# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-15 17:27
from __future__ import unicode_literals

from django.db import migrations
from django.utils import timezone
from polls.models import Question

def load_intial_data(apps, schema_editor):
    for i in range(10):
        q = Question(question_text="From Migration number " + str(i), pub_date=timezone.now())
        q.save()

class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_question_question_text_alt'),
    ]

    operations = [
        migrations.RunPython(load_intial_data),
    ]
